import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MenuBar from "@/lib/Menubar/Menubar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <title>Ros GUI Controller</title>
      </head>
      <body>
        <header>
          <MenuBar />
        </header>
        {children}
        <footer>
          <small></small>
        </footer>
      </body>
    </html>
  );
}
